plugins {
    id 'java'
    id 'application'
}

group = 'me.tamkungz'
version = '0.1.2'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'me.tamkungz.nilloaderinstaller.Main'
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
    archiveFileName = "NilLoaderInstaller-${project.version}+unofficial.jar"
}